apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
    dash.ulagbulag.io/subject: mobilex-exp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      dash.ulagbulag.io/subject: mobilex-exp
  template:
    metadata:
      labels:
        app: backend
        dash.ulagbulag.io/subject: mobilex-exp
    spec:
      containers:
      - name: backend
        image: docker.io/isnan7897/lck_news_back:v0.6
        ports:
        - name: http
          protocol: TCP
          containerPort: 8000
        env:
        - name: SQLALCHEMY_DATABASE_URL
          value: "sqlite:///./test.db"  # Update this if you use a different database
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai
              key: OPENAI_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    dash.ulagbulag.io/subject: mobilex-exp
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Secret
metadata:
  name: openai
stringData:
  OPENAI_API_KEY: "sk-proj-OYPQSYErvElP3Hkl7vqhT3BlbkFJZgKADqTwdsEoqGXBqwrP"
