apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
    dash.ulagbulag.io/subject: mobilex-exp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
      dash.ulagbulag.io/subject: mobilex-exp
  template:
    metadata:
      labels:
        app: backend
        dash.ulagbulag.io/subject: mobilex-exp
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        ports:
        - name: http
          protocol: TCP
          containerPort: {{ .Values.backend.service.port }}
        env:
        - name: SQLALCHEMY_DATABASE_URL
          value: "{{ .Values.backend.env.SQLALCHEMY_DATABASE_URL }}"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai
              key: OPENAI_API_KEY
